name: Update Drama List

on:
  schedule:
    - cron: '0 0 * * *' # हर रात 12 बजे अपने आप चलेगा
  workflow_dispatch: # बटन दबाकर खुद चलाने के लिए

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install yt-dlp
        
      - name: Run Scraper
        run: python scraper.py
        
      - name: Commit and Push changes
        run: |
          git config --global user.name 'rohitkumar-io'
          git config --global user.email 'rohitkumar-io@users.noreply.github.com'
          git add movies.json
          git commit -m "Auto Update: Latest Dramas" || exit 0
          git push
